version: '3'

tasks:

  dev:
    cmds:
      - go run cmd/main.go

  install:
    cmds:
      - go mod tidy

  lint:
    cmds:
      - gofmt -l -w .
      - gci write -s standard -s default -s 'prefix(loadtest-api-go)' -s localmodule .
